#!/bin/sh


./web/vendor/bin/pint --config ./web/pint.json

./web/vendor/bin/phpstan analyse --memory-limit 1G -c ./web/phpstan.neon.dist $files

status=$?


if [ $status != 0 ]; then
    echo "phpstan analysis filed. Commit aborted."
    exit 1
fi


